kossiitkgp/KWoC-Backend

- go.mod
- go.sum
- main.go
Adding CORS support using Gorilla handlers (added dependency)
Currently all foreign domains are allowed.
> Added CORS support

- controllers/mentor.go
- main.go
Mentor OAuth working fine. Tested using postman
Couldn't test from frontend as it was giving CORS error in spite of enabling it in `main.go`
Once check if it is the right way or not
if not please correct and push it
> Added function for Mentor OAuth

- .github/workflows/deploy-action.yml
Signed-off-by: sahil-shubham <sahil.shubham2000@gmail.com>
> CD pipeline setup 

- controllers/mentor.go
- controllers/project.go
- routes/mentor.go
> Get all Mentor Endpoint

- controllers/mentor.go
- controllers/project.go
- models/project.go
- routes/project.go
- utils/loginrequired.go
This route now return data of Mentors and Secondary Mentor in the same json
> Add Projects Endpoint update

- controllers/project.go
Communication Channel can be updated now
> edit Communication channel

- controllers/project.go
Removed unnecessary log statements..
> Removed log statement

- README.md
- Removed old set up steps.
- Added docker build steps with important note.
> Adding building commands for dockerfile

- .github/workflows/golangci-lint.yml
- controllers/UserOAuth.go
- utils/jsonio.go
> Fix linter

- controllers/healthcheck.go
- main.go
- routes/healthcheck.go
Trying again after trying to rebase
> Adding a healthcheck route v2

- .dockerignore
- fly.toml
- Add dockerignore
- Add fly.toml that manages deployement on fly.io
> Add Deployement configs

- .github/workflows/fly-deploy.yml
> add ci cd for auto deployment

- controllers/healthcheck.go
- go.mod
- go.sum
- main.go
> Added sentry setup

- controllers/stats-overall.go
- models/stats.go
- routes/stats.go
> Stats API v2 - Overall Stats Endpoint

- routes/stats.go
Hotfix: Add Permissive cors middleare
> cors bugfix

- main.go
> Cors issue

- routes/stats.go
- changed stats api POST endpoint to GET
> Update stats endpoint method type

- .env.template
- README.md
Closes #97 
Closes #77 
- Added a ToC.
- Added documentation for setting up the local dev environment.
- Documented the environment variables used.
- Documented the endpoints.
- Documented the project structure.
> Updated the docs (README)

- controllers/mentor.go
- controllers/student.go
Closes #95
- Added a check in mentor and student controllers for existing entries and return an error to prevent multiple registrations.
> Fixed Multiple Registrations Bug

- controllers/healthcheck.go
- server/routes.go
The Ping function responds with "pong" and returns the latency. The HealthCheck function checks the server and database status. If the database connection fails, it returns a 500 status code. If the ping to the database fails, it also returns a 500 status code. Otherwise, it returns a 200 status code and "OK".
#111
> feat(healthcheck.go): add Ping and HealthCheck routes

- controllers/oauth.go
- utils/json.go
Commit cherry picked from v2-projects-get-route, to a branch branched from v2-dev
> separate PR for "feat: added a json response util"

- controllers/mentor.go
- controllers/oauth.go
- controllers/student.go
- utils/json.go
> [v2] Util for Json decoding 

- controllers/healthcheck_test.go
> [v2] added healthcheck test script

- controllers/student.go
- controllers/student_test.go
- server/routes.go
- Added `/student/bloglink/` (POST) endpoint. [Issue #126]
- Added tests for `/student/bloglink/`
> [v2] Student Blog link route

- controllers/project_update.go
- controllers/project_update_test.go
- server/routes.go
- Added the `/project/update` route.
> [v2] Update Project Route

- controllers/mentor.go
- controllers/mentor_test.go
- server/routes.go
closes #128 
- Added `/mentor/all/` GET route
- Added tests for the same
> [v2] `/mentor/all/` route

- .github/workflows/test_and_lint.yml
Modified "Testing and Linting" workflow to also trigger on push to v2-dev and main (for futurer)
> [v2] added workflow for push

- controllers/mentor_test.go
- controllers/student.go
- controllers/student_test.go
- server/routes.go
#127 
- Adding `/student/dashboard/` route
- Adding tests for the same
> [v2] Adding `/student/dashboard/` route

- .github/workflows/swagger_docs.yml
- README.md
- cmd/backend.go
- controllers/student.go
Added support for security annotation for the endpoints which require login. Also fixed a bug in the workflow.
> [v2] Added security JWT annotations support 

- README.md
- controllers/common_test.go
- controllers/mentor.go
- controllers/mentor_test.go
- controllers/project_fetch_test.go
- controllers/project_reg.go
- controllers/project_reg_test.go
- controllers/project_update.go
- controllers/project_update_test.go
- controllers/student.go
- controllers/student_test.go
- utils/json.go
- utils/log.go
> [v2]  Standardized JSON response format

- controllers/mentor_test.go
- controllers/project_fetch_test.go
- controllers/project_reg_test.go
- controllers/project_update_test.go
- controllers/student_test.go
- utils/json.go
> Renamed `code` to `status_code` in Responses

- code_of_conduct.md
> code_of_conduct.md file added

- .github/workflows/swagger_docs.yml
> Fix swagger documentation workflow

- .github/workflows/swagger_docs.yml
Closes #185 for sure this time.
> Fixed swaggo docs
